In [ ]:
import cv2
import pandas as pd

img = cv2.imread('puppy.jpg')

if img is None:
    print("Image not found")
else:
    

    pixels = img.reshape(-1, 3)

  
    df = pd.DataFrame(
        pixels,
        columns=['Blue', 'Green', 'Red']
    )

    
    df.to_excel(
        'pixel_values.xlsx',
        index=False
    )

    print("Pixel values saved to Excel")

Pixel values saved to Excel


In [ ]:
import cv2

img = cv2.imread('puppy.jpg')

print(img)

[[[ 17  37  14]
  [ 17  37  14]
  [ 18  38  15]
  ...
  [ 50  78  55]
  [ 49  77  54]
  [ 48  76  53]]

 [[ 17  37  14]
  [ 17  37  14]
  [ 18  38  15]
  ...
  [ 51  79  56]
  [ 50  78  55]
  [ 49  77  54]]

 [[ 18  38  15]
  [ 18  38  15]
  [ 18  38  15]
  ...
  [ 53  81  58]
  [ 52  80  57]
  [ 51  79  56]]

 ...

 [[132 195 175]
  [129 194 173]
  [124 191 170]
  ...
  [104 192 168]
  [106 194 170]
  [107 195 171]]

 [[132 197 176]
  [128 195 174]
  [123 192 171]
  ...
  [104 192 168]
  [105 193 169]
  [106 194 170]]

 [[130 197 176]
  [128 195 174]
  [123 192 171]
  ...
  [103 194 169]
  [103 194 169]
  [103 194 169]]]
